# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dc2994a453a6367c975b0e28c9cc001eda81bbcf07fb19bdeeab95d79680e97f04dfed8e184b3b736e263ea8dd19a511fceddaeb71ed0d102b08b502a8903bf

test:
  secret_key_base: 45cba7b924cd178f1ad6f891f14cf6c5c72aad18004f3392ca2576b8f7430218566fc01c83eafd532897f3fc3df13b8d0265b7feb5ba1fef5a87dd97c662ebc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
